#!/usr/bin/env bash
# One-shot rename: Helmor → Winthorpe.
# Run from repo root. Idempotent (safe to re-run).
#
# Substitution priority matters — most specific first to avoid double-replace.

set -euo pipefail

cd "$(dirname "$0")/.."

# Files / paths that should NOT be touched by content substitution.
# Reasons:
#   CHANGELOG.md         — historical helmor changelog, preserves provenance
#   .changeset/calm-*    — in-flight upstream changesets, leave as evidence
#   .changeset/neat-*    — same
#   LICENSE              — Apache 2.0, no name reference
#   NOTICE               — handled separately (preserves trademark attribution)
#   *.lock               — regenerated by package managers
#   bun.lock files       — regenerated
#   *.snap (rust)        — auto-regenerated by cargo insta on next test run,
#                          but we rename the files themselves so paths match
EXCLUDE_FILES=(
  "CHANGELOG.md"
  ".changeset/calm-models-dance.md"
  ".changeset/neat-branches-divide.md"
  "LICENSE"
  "NOTICE"
  "bun.lock"
  "sidecar/bun.lock"
  "src-tauri/Cargo.lock"
  "scripts/rename-to-winthorpe.sh"
)

# Build a `find` exclusion expression for those files.
build_excludes() {
  local args=()
  for f in "${EXCLUDE_FILES[@]}"; do
    args+=( -not -path "./$f" )
  done
  printf '%s\n' "${args[@]}"
}

mapfile -t EXCLUDE_ARGS < <(build_excludes)

echo "==> 1/5  In-file substitutions"

# Collect candidate text files first (non-binary, not in excluded dirs).
mapfile -t TARGETS < <(
  find . -type f \
    -not -path "./node_modules/*" \
    -not -path "./.git/*" \
    -not -path "./target/*" \
    -not -path "./dist/*" \
    -not -path "./sidecar/dist/*" \
    -not -path "./sidecar/node_modules/*" \
    -not -path "./apps/*/node_modules/*" \
    -not -path "./apps/*/.next/*" \
    -not -path "./.bundle-cache/*" \
    -not -path "./sidecar/.bundle-cache/*" \
    "${EXCLUDE_ARGS[@]}" \
    \( -name "*.rs" -o -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.mjs" \
       -o -name "*.json" -o -name "*.toml" -o -name "*.md" -o -name "*.yml" -o -name "*.yaml" \
       -o -name "*.html" -o -name "*.css" -o -name "*.sh" -o -name "*.bat" -o -name "*.ps1" \
       -o -name "*.example" -o -name "*.gitignore" -o -name "Dockerfile" -o -name "*.plist" \
       -o -name "*.snap" \) \
    -print
)

echo "    ${#TARGETS[@]} candidate files"

# Substitution rules in priority order. Most specific first.
# Format: pattern|replacement
SUBSTITUTIONS=(
  's|ai\.helmor\.desktop|com.plsft.winthorpe|g'
  's|helmor-thinking-indicator|winthorpe-thinking-indicator|g'
  's|helmor-logo-animated|winthorpe-logo-animated|g'
  's|helmor-logo-light|winthorpe-logo-light|g'
  's|helmor-logo-dark|winthorpe-logo-dark|g'
  's|helmor-logo-1024|winthorpe-logo-1024|g'
  's|helmor-logo-liquid-flow|winthorpe-logo-liquid-flow|g'
  's|helmor-logo-animation|winthorpe-logo-animation|g'
  's|helmor-logo|winthorpe-logo|g'
  's|helmor-banner|winthorpe-banner|g'
  's|helmor-screenshot-mix|winthorpe-screenshot-mix|g'
  's|helmor-screenshot-dark|winthorpe-screenshot-dark|g'
  's|helmor-screenshot-light|winthorpe-screenshot-light|g'
  's|helmor-sidecar|winthorpe-sidecar|g'
  's|helmor-cli|winthorpe-cli|g'
  's|helmor-dev|winthorpe-dev|g'
  's|helmor_lib|winthorpe_lib|g'
  's|helmor\.json|winthorpe.json|g'
  's|HELMOR_|WINTHORPE_|g'
  's|Helmor|Winthorpe|g'
  's|helmor|winthorpe|g'
)

count=0
for f in "${TARGETS[@]}"; do
  # Skip binary files defensively
  if file "$f" 2>/dev/null | grep -qE 'binary|image|video|audio'; then
    continue
  fi
  modified=0
  for sub in "${SUBSTITUTIONS[@]}"; do
    if grep -qE "${sub#s|}" "$f" 2>/dev/null; then
      sed -i "$sub" "$f"
      modified=1
    fi
  done
  if [ $modified -eq 1 ]; then
    count=$((count + 1))
  fi
done
echo "    Modified $count files"

echo "==> 2/5  Renaming files"

# Use git mv when possible so history follows.
git_mv() {
  local src="$1" dst="$2"
  if [ -e "$src" ] && [ ! -e "$dst" ]; then
    mkdir -p "$(dirname "$dst")"
    git mv "$src" "$dst" 2>/dev/null || mv "$src" "$dst"
    echo "    $src → $dst"
  fi
}

# Component files
git_mv "src/components/helmor-thinking-indicator.tsx" "src/components/winthorpe-thinking-indicator.tsx"
git_mv "src/components/helmor-logo-animated.tsx" "src/components/winthorpe-logo-animated.tsx"

# CLI binary source
git_mv "src-tauri/src/bin/helmor-cli.rs" "src-tauri/src/bin/winthorpe-cli.rs"

# helmor.json scripts manifest
git_mv "helmor.json" "winthorpe.json"

# Skill directories
git_mv ".codex/skills/helmor-cli" ".codex/skills/winthorpe-cli"
git_mv ".codex/skills/helmor-cli/references/helmor-help.md" ".codex/skills/winthorpe-cli/references/winthorpe-help.md" || true
git_mv ".codex/skills/helmor-release" ".codex/skills/winthorpe-release" || true
git_mv ".claude/skills/helmor-release" ".claude/skills/winthorpe-release" || true

# Asset renames (image content stays helmor-branded as a placeholder)
for asset in \
    src/assets/helmor-banner.mp4 \
    src/assets/helmor-logo-1024.png \
    src/assets/helmor-logo-animation.json \
    src/assets/helmor-logo-light.png \
    src/assets/helmor-logo-liquid-flow.webm \
    src/assets/helmor-logo.png \
    src/assets/helmor-screenshot-dark.png \
    src/assets/helmor-screenshot-light.png \
    src/assets/helmor-screenshot-mix.png \
    src-tauri/icons/brand/helmor-logo-dark.png \
    src-tauri/icons/brand/helmor-logo-dark.svg \
    src-tauri/icons/brand/helmor-logo-light.png \
    src-tauri/icons/brand/helmor-logo-light.svg \
    apps/marketing/public/helmor-logo-dark.svg \
    apps/marketing/public/helmor-logo-light.svg \
    apps/marketing/public/helmor-screenshot-dark.png \
    apps/marketing/public/helmor-screenshot-light.png; do
  if [ -e "$asset" ]; then
    new=$(echo "$asset" | sed 's|helmor|winthorpe|g')
    git_mv "$asset" "$new"
  fi
done

# Snapshot files (will be regenerated, but rename so test names match)
for snap in src-tauri/src/agents/streaming/snapshots/helmor_lib__*.snap; do
  [ -e "$snap" ] || continue
  new=$(echo "$snap" | sed 's|helmor_lib|winthorpe_lib|g')
  git_mv "$snap" "$new"
done

echo "==> 3/5  NOTICE — preserve original attribution, append Winthorpe modification notice"

cat > NOTICE <<'EOF'
================================================================================
Winthorpe — a Windows-first fork of Helmor
================================================================================

Winthorpe is derived from Helmor (https://github.com/dohooo/helmor), originally
authored by Caspian Zhao and Nathan Lian. Per the Apache 2.0 trademark notice
in upstream Helmor's NOTICE, this fork ships under a distinct name and does
not use the "Helmor" mark or logo to identify itself.

This file preserves upstream Helmor's NOTICE in full below for attribution.
Per Apache 2.0 Section 4(b), source files modified as part of the Windows port
carry change notices in their headers where modifications are non-trivial.

================================================================================
Upstream NOTICE (Helmor)
================================================================================

Helmor
Copyright 2026 Caspian Zhao, Nathan Lian

This product is licensed under the Apache License, Version 2.0 (the "License");
you may not use this product except in compliance with the License. A copy of
the License is distributed with this product in the LICENSE file, and is also
available at https://www.apache.org/licenses/LICENSE-2.0.

================================================================================
Attribution
================================================================================

Per Section 4(d) of the Apache License 2.0, any redistribution or derivative
work must include a readable copy of this NOTICE file, and must retain the
copyright and attribution statements above.

Per Section 4(b), any modified source files must carry prominent notices
stating that the files have been changed, so downstream users can trace
modifications back to their origin.

================================================================================
Trademark Notice
================================================================================

"Helmor" and the Helmor logo are trademarks of Caspian Zhao and Nathan Lian.

The Apache License 2.0 grants you rights to use, modify, and redistribute the
software source code. It does NOT grant you the right to use the "Helmor"
name, logo, brand assets, or any confusingly similar mark to identify your
own product, fork, or service. Forks must ship under a distinct name.

For commercial use of the "Helmor" name or logo, contact the authors.

================================================================================
Third-Party Components
================================================================================

This product bundles or depends on the following third-party components,
each licensed under its own terms. See the respective project pages for
license text:

- Tauri (tauri-apps/tauri) — MIT / Apache-2.0
- React (facebook/react) — MIT
- Bun (oven-sh/bun) — MIT
- Claude Agent SDK (@anthropic-ai/claude-agent-sdk) — Anthropic's terms
- Codex SDK (@openai/codex-sdk) — OpenAI's terms
EOF

echo "==> 4/5  Sanity checks"
remaining=$(grep -rIli 'helmor' \
  --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=target \
  --exclude-dir=dist --exclude-dir=.bundle-cache --exclude-dir=.next \
  --exclude=CHANGELOG.md --exclude='calm-models-dance.md' \
  --exclude='neat-branches-divide.md' --exclude=NOTICE \
  --exclude='*.lock' --exclude='rename-to-winthorpe.sh' \
  . 2>/dev/null | wc -l)
echo "    Files still containing 'helmor' (case-insensitive, outside expected exclusions): $remaining"

echo "==> 5/5  Done"
echo "Next steps:"
echo "  1. Review with: git diff --stat"
echo "  2. Lockfiles will regenerate on next install/build"
echo "  3. Snapshot files will regenerate on next 'cargo test'"
echo "  4. Brand image content still helmor-branded — replace with Winthorpe artwork later"
